# this is a github actions workflow file that is designed to deploy Ineffa to a google cloud platform (gcp) instance.
# while it is configured for gcp, the underlying principles and structure can be adapted for other cloud providers.

name: Deploy Ineffa

permissions:
  contents: read
  pull-requests: write

# specifies the trigger for this workflow.
on:
    push:
        branches: [ main ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4 # pre-built action from the github marketplace.

            - name: SSH and Deploy
              uses: appleboy/ssh-action@v1.0.3 # a community-built action for ssh.
              with:
                # the following are parameters for the ssh-action
                host: ${{ secrets.IP }}       # the ip of the gcp instance.
                username: ${{ secrets.User }}  # the username for the ssh connection.
                key: ${{ secrets.SSH_KEY }}     # the private ssh key for authentication.
                # the script to be executed on the remote server.
                script: |
                    cd $HOME/ineffa/discord-gemineffa-v1
                    git fetch --all
                    git reset --hard origin/main
                    npm install --production
                    pm2 startOrReload ecosystem.config.js --update-env
                    pm2 save